name: Tangled

on:
  push:
    branches:
      - main

jobs:
  tangled:
    runs-on: ubuntu-latest
    steps:
      - uses: gwennlbh/to-tangled@v0.3
        with:
          repo: mkizka.dev/pdsadmin-web
          ssh-key: ${{ secrets.TANGLED_SECRET_KEY }}
