name: Tangled

on:
  push:
    branches:
      - main

jobs:
  tangled:
    runs-on: ubuntu-latest
    steps:
      - uses: gwennlbh/to-tangled@c2895c0be7bac6c87ca03ed04a649d66072a026e # v0.4
        with:
          repo: mkizka.dev/pdsadmin-web
          ssh-key: ${{ secrets.TANGLED_SECRET_KEY }}
